server.port=8080

# --- Connexion Aiven MySQL ---
spring.datasource.url=jdbc:mysql://mysql-34c8d55a-scolarix-bd.i.aivencloud.com:10152/defaultdb?ssl-mode=REQUIRED&useSSL=true
spring.datasource.username=avnadmin
# Remplacez les étoiles ci-dessous par votre vrai mot de passe Aiven
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate 7+ détecte le dialecte automatiquement, vous pouvez laisser ou commenter la ligne suivante
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect